# Generated by Django 4.2.5 on 2023-11-15 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('biography', models.TextField(blank=True)),
                ('species', models.CharField(choices=[('d', 'Dog'), ('c', 'Cat'), ('o', 'Other')], default='d', max_length=1)),
                ('status', models.CharField(choices=[('a', 'Available'), ('u', 'Unavailable')], default='a', max_length=1)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('breed', models.CharField(max_length=255)),
                ('colour', models.CharField(choices=[('w', 'White'), ('br', 'Brown'), ('be', 'Beige'), ('g', 'Grey'), ('bl', 'Black'), ('o', 'Other')], default='w', max_length=2)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=1)),
                ('size', models.CharField(choices=[('s', 'Small (5-10kg)'), ('m', 'Medium (10-15kg)'), ('l', 'Large (15-30kg)')], default='s', max_length=1)),
                ('location', models.CharField(max_length=255)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
