# Generated by Django 4.2.7 on 2023-11-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='./P2/PetPal/pets/pictures/'),
        ),
    ]
