# Generated by Django 4.2.5 on 2023-11-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_last_updated_pet_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='colour',
            field=models.CharField(choices=[('white', 'White'), ('brown', 'Brown'), ('beige', 'Beige'), ('grey', 'Grey'), ('black', 'Black'), ('other', 'Other')], default='white', max_length=5),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(choices=[('small', 'Small (5-10kg)'), ('medium', 'Medium (10-15kg)'), ('large', 'Large (15-30kg)')], default='small', max_length=6),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('other', 'Other')], default='dog', max_length=5),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=11),
        ),
    ]
