# Generated by Django 4.2.5 on 2023-11-15 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('applicantOtherPetsDetails', models.TextField()),
                ('applicantOtherPetsNeutered', models.BooleanField(default=False)),
                ('applicantOutdoorArea', models.BooleanField(default=False)),
                ('applicantAnimalAlone', models.BooleanField(default=False)),
                ('applicantHistory', models.BooleanField(default=False)),
                ('applicantProperty', models.TextField()),
                ('applicantHome', models.TextField()),
                ('applicantWork', models.TextField()),
                ('applicantDetails', models.TextField()),
                ('PENDING', models.BooleanField(default=True)),
                ('ACCEPTED', models.BooleanField(default=False)),
                ('DENIED', models.BooleanField(default=False)),
                ('WITHDRAWN', models.BooleanField(default=False)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_applicant', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_shelter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
