# Generated by Django 4.2.7 on 2023-11-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='ACCEPTED',
        ),
        migrations.RemoveField(
            model_name='application',
            name='DENIED',
        ),
        migrations.RemoveField(
            model_name='application',
            name='PENDING',
        ),
        migrations.RemoveField(
            model_name='application',
            name='WITHDRAWN',
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('DENIED', 'DENIED'), ('WITHDRAWN', 'WITHDRAWN')], default='PENDING', max_length=10),
        ),
    ]
