# Generated by Django 5.0 on 2023-12-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_remove_application_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicantAnimalAlone',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicantHistory',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicantOtherPetsNeutered',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicantOutdoorArea',
            field=models.TextField(),
        ),
    ]
