# Generated by Django 5.0 on 2023-12-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_applicantanimalalone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicantAllergy',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
