# Generated by Django 4.2.7 on 2023-12-08 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShelterBlog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0002_alter_shelterreviewcomment_commenter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelterBlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelter_blog_comments', to='ShelterBlog.shelterblog')),
                ('commenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_blog_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
