# Generated by Django 4.2.7 on 2023-12-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_shelterblogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelterreviewcomment',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
