# Generated by Django 4.2.7 on 2023-12-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShelterBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelterblog',
            name='title',
            field=models.CharField(default='Title', max_length=255),
        ),
    ]
