# Generated by Django 4.2.7 on 2023-12-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShelterBlog', '0003_alter_shelterblog_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelterblog',
            name='likes',
        ),
        migrations.AddField(
            model_name='shelterblog',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
